name: ben parnell's blog
description: adventures in software engineering
meta_description: "ben parnell's blog. adventures in software engineering."

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://benjaminparnell.github.io'
google_analytics: 'UA-64405718-1'
disqus_shortname: 'benparnellblog'

# Details for the RSS feed generator
url:            'http://benjaminparnell.github.io'
author:         'Ben Parnell'
authorTwitter:  'benjaminparnell'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
